### ISSUE TITLE
Mekanism machines keep pulling power and translation error

### ISSUE THREAD

**Issue by GuntherDW** [CyclopsMC/EnergySynergy#5] opened 2017-01-22 13:52 UTC
When I installed this mod my Mekanism machines started drawing insane amounts of power, even when said buffer is completely full.

Without EnergySynergy
http://i.imgur.com/odG2LzL.png
With EnergySynergy enabled (and EU blacklisted in Mek, otherwise the energy used is *10)
http://i.imgur.com/UiwOQJQ.png

The 1 RF/t extra load is from the EnderIO Power Monitor block attached to capacitor bank.

In both cases you can use the machine, it gets said power successfully.
Here it is processing iron without synergy
http://i.imgur.com/EgNg6QO.png

The power scaling also affects the other way around too though.
When for example Mekanism's fusion reactor is set to produce 2M RF/t (injection rate:  20), it'll export close to 5M RF/t.

I already have an issue at SonarSonic's Flux Networks issue tracker because I thought it was something on their end. Apparently it was't?
https://github.com/SonarSonic/Flux-Networks/issues/38

Versions :
- Minecraft : 1.10.2
- Forge : 12.18.3.2221
- CyclopsCore : 1.9.4-0.9.0
- EnergySynergy : 1.10.2-1.1.1
- Mekanism : 1.10.2-9.2.1.298

**Comment by rubensworks** [comment] 2017-01-22 14:05
@GuntherDW Have you reported this to Mekanism already?
The only thing this mod do is adding additional capabilities to machines and items, so it does nothing actively by itself.
My guess is that Mekanism consumes from one energy interface type first (e.g. RF), and then also looks for Tesla and/or Forge Energy and also consumes that amount of energy from them, while it should only consume energy from the first possible energy type.

**Comment by GuntherDW** [comment] 2017-01-22 14:21
I haven't yet, no.

Mekanim's power network indeed is kind of... weird. It has all kinds of quirks.
But I don't think, judging by the code in https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/util/CableUtils.java that it does what you say it does.

Aidan has been busy for so long. His mod suffers from it. For example these issues
https://github.com/aidancbrady/Mekanism/issues/4116
https://github.com/aidancbrady/Mekanism/issues/4143

There is someone attempting to rewrite and update a lot of the codebase (ThatGamerBlue in the issue reports from Mekanism), but that "port" is still in its very early stages it seems.

**Comment by rubensworks** [comment] 2017-01-22 14:24
Let me know once you've opened the issue. I'd be happy to help resolving this problem, but I doubt it is something that's caused by Energy Synergy.

**Comment by GuntherDW** [comment] 2017-01-22 20:20
I've created the issue and linked them here as well.
(Sorry for the delay, had family over for a while)

**Comment by sscards55** [comment] 2017-02-20 07:27
If I could make a suggestion.
Could you make a config file for whitelisting certain TileEntities. Populate the list with all TileEntities on first creation. Save a seperate file that contains a list of all previously registered TileEntities, so that when a user adds a mod new TileEntities will also be added to the whitelist.

**Comment by rubensworks** [comment] 2017-02-20 09:23
@sscards55 Could you create a separate issue for this?

**Closed as completed** 2024-10-28 14:27 UTC
Labels: bug, other mod, mc-1.10
